version: "2"

services:
  powa-repository:
    image: powateam/powa-archivist-12
    container_name: powa-standalone-repository
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  powa-web:
    image: powateam/powa-web
    container_name: powa-standalone-web
    ports:
      - 8888:8888
    links:
      - powa-repository
